### ISSUE TITLE
Incorrect app title after the installation 

### ISSUE THREAD

**Issue by iamranger** [rarimo/FreedomToolAndroid#1]
"Pools 2024" instead of "Polls 2024".

Platform - Pixel 7a
![Screenshot_20240308-132458](https://github.com/rarimo/FreedomToolAndroid/assets/12720520/e69d6afb-0a4d-488e-8360-6ce195d6fa80)

**Comment by ApereLieZ** [comment]
@iamranger  Thanks for your comment.
We have already changed the name of the application
